# Generated by Django 4.1 on 2022-09-03 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coordinates', '0004_alter_groupleader_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
