# Generated by Django 4.1 on 2022-09-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0007_alter_groupmember_group_alter_groupmember_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphtask',
            name='processed',
        ),
        migrations.AddField(
            model_name='graphtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
